name: json2dart_serialization
description: 一个网页版本的json转dart库
# version: 1.0.0
#homepage: https://www.example.com
#author: Caijinglong <email@example.com>

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

#dependencies:
#  path: ^1.4.1
dependencies:
  # Your other regular dependencies here
  json_annotation:
  intl: 

dev_dependencies:
  build_runner: 
  build_web_compilers: 
  json_serializable: 